#! /bin/sh

set -ex

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

[ -d cross-detect ] || git clone https://github.com/mintsuki/cross-detect.git
[ -d freestanding-headers ] || git clone https://github.com/mintsuki/freestanding-headers.git
[ -d libgcc-binaries ] || git clone https://github.com/mintsuki/libgcc-binaries.git
if ! [ -d printf ]; then
    mkdir printf
    curl -Lo printf/printf.c https://github.com/eyalroz/printf/raw/master/src/printf/printf.c
    curl -Lo printf/printf.h https://github.com/eyalroz/printf/raw/master/src/printf/printf.h
fi

automake_libdir="$(automake --print-libdir)"

mkdir -p build-aux
cp "${automake_libdir}/install-sh" build-aux

autoreconf -fvi
